#pragma once  

enum UI_BuySellButtonFrames : uint16_t
{
	BUYSELLBTN_BLANK = 0,
	BUYSELLBTN_BLANK_PRESSED = 1,
	BUYSELLBTN_BUY = 2,
	BUYSELLBTN_BUY_PRESSED = 3,
	BUYSELLBTN_SELL = 4,
	BUYSELLBTN_SELL_PRESSED = 5,
	BUYSELLBTN_REPAIR = 6,
	BUYSELLBTN_REPAIR_PRESSED = 7,
	BUYSELLBTN_CANCEL = 8,
	BUYSELLBTN_CANCEL_PRESSED = 9,
	BUYSELLBTN_CLOSE = 10,
	BUYSELLBTN_CLOSE_PRESSED = 11,
	BUYSELLBTN_PREVIOUS = 12,
	BUYSELLBTN_PREVIOUS_PRESSED = 13,
	BUYSELLBTN_NEXT = 14,
	BUYSELLBTN_NEXT_PRESSED = 15,
	BUYSELLBTN_CONFIRM = 16,
	BUYSELLBTN_CONFIRM_PRESSED = 17,
	// Expansion only
	BUYSELLBTN_REPAIRALL = 18,
	BUYSELLBTN_REPAIRALL_PRESSED = 19,
	BUYSELLBTN_PARTY = 20,
	BUYSELLBTN_PARTY_PRESSED = 21,

};

enum UI_ItemBackgroundColor {
	UI_ItemBgColor_Red,
	UI_ItemBgColor_Green,
	UI_ItemBgColor_Navy,
	UI_ItemBgColor_Olive,
	UI_ItemBgColor_Brown,
	UI_ItemBgColor_COUNT
};
