#pragma once

enum DisplayType
{
	DISPLAYTYPE_INVALID,
	DISPLAYTYPE_GDI,
	DISPLAYTYPE_UNK,
	DISPLAYTYPE_DDRAW,
	DISPLAYTYPE_GLIDE,
	DISPLAYTYPE_OPENGL,
	DISPLAYTYPE_DIRECT3D,
	DISPLAYTYPE_RAVE,
	NUMBER_OF_DISPLAYTYPES
};
